[basic]
key = ""

[minecraft]
username = "mcf-bet-public"
serverip = "sg.mcfallout.net"
whitelist = ["lidahehowasin"]

[bet]
emax = 50000000
emin = 1
cmax = 1
cmin = 1
eodds = 1.85
codds = 1.85
bet_position = []

[discord]
enabled = 0
bot_token = ""
bot_client_id = ""
guild_id = ""

[discord_channels]
console = ""
command_record = ""
bet_record = ""
status = ""
link = ""
errors = ""

